### ISSUE TITLE
PHP: implement hashing

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/InternalO#3]
Password comparison currently does not implement hashing.

**Comment by Abdur-rahmaanJ** [comment]
see this: https://stackoverflow.com/questions/30279321/how-to-use-password-hash ^^_

**Comment by jonathan-alvaro** [comment]
Hi, can I try this out?

**Comment by vijay94** [comment]
Hi Abdur, I have implemented hashing password. Please review my PR #9 .
